### ISSUE TITLE
Gulp Watch not behaving

### ISSUE THREAD

**Issue by gurtfrobe** [friendlymachine/atlas#1]
`gulp watch` is monitoring the _styles.scss_ file only, which is simply importing the other styles.

When I update _/layout/_layout.scss_, the `watch` task doesn't fire as _styles.scss_ technically hasn't changed.

**Comment by friendlymachine** [comment]
Good catch! I can get to this later in the week, but I'll also accept a pull request if you want to take a crack at it. :)

**Comment by friendlymachine** [comment]
OK, I think I have this fixed. Closing this issue.

**Comment by gurtfrobe** [comment]
Nice work!
